[package]
name = "substratee_client_example"
version = "0.1.0"
authors = ["Marcel Frei <marcel.frei@scs.ch>"]
edition = "2018"

[dependencies]
ws = "*"
env_logger = "*"
tiny-bip39 = "0.6.0"
schnorrkel = "0.1"
rand = "0.6"
hex-literal = "0.2.0"
hex = "0.3"
clap = { version = "2.33", features = [ "yaml" ] }
serde_json = "1.0"
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
blake2-rfc = { version = "0.2.18", default-features = false}

substrate-api-client = { git = "https://github.com/scs/substrate-api-client", default-features = false }
my_node_runtime = { package = "substratee-node-runtime", git = "https://github.com/scs/substraTEE-node", features=["no_global_allocator"] }

substrate_bip39 = { package="substrate-bip39", git = "https://github.com/paritytech/substrate-bip39" }

node-primitives = { git = 'https://github.com/paritytech/substrate', rev = '6e67eff0653677d3d01980ca822c4b8a227914a3' }
substrate-keyring = { git = 'https://github.com/paritytech/substrate', rev = '6e67eff0653677d3d01980ca822c4b8a227914a3' }
runtime_primitives = { package = "sr-primitives", git = 'https://github.com/paritytech/substrate', rev = '6e67eff0653677d3d01980ca822c4b8a227914a3', default-features = false }
primitives = { package = "substrate-primitives", git = 'https://github.com/paritytech/substrate', rev = '6e67eff0653677d3d01980ca822c4b8a227914a3' }

sgx_crypto_helper = { git = "https://github.com/baidu/rust-sgx-sdk", default-features = false}
system = { package = "srml-system", git = 'https://github.com/paritytech/substrate', rev = '6e67eff0653677d3d01980ca822c4b8a227914a3' }
