[package]
name = "SealedKeyEnclave"
version = "1.0.0"
authors = ["Alain Brenzikofer"]

[lib]
name = "sealedkeyenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk"}
sgx_tseal = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk", features=["untrusted_fs", "backtrace"] }
sgx_rand = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-crypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-base58 = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper = { package="sgx_tcrypto_helper", git = "https://github.com/baidu/rust-sgx-sdk" }

[target.'cfg(target_env = "sgx")'.dependencies]
sgx_crypto_helper = { package="sgx_tcrypto_helper", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
serde_json = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize_derive = { git = "https://github.com/baidu/rust-sgx-sdk" }
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
blake2-rfc = { git = "https://github.com/brenzi/blake2-rfc.git", default-features = false}
environmental = { version = "1.0.1", default-features= false}
# !!!!!! no_std trouble https://github.com/w3f/schnorrkel/issues/31
#schnorrkel = { git = "https://github.com/w3f/schnorrkel.git", default-features = false, features=["alloc", "u64_backend"] }

#only listed to get no_global_allocator feature in
rstd = { package = "sr-std", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false, features=["no_global_allocator"]}
#only listed to get no_panic_handler and no_oom  features in
runtime_io = { package = "sr-io", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false, features=["no_panic_handler", "no_oom", "sgx"]}#, "debug"]}
#only listed to get features in
sandbox = { package = "sr-sandbox", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false, features=["sgx"]}

primitives = { package = "substrate-primitives", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }
#my_node_runtime = { package = "substratee-node-runtime", git = "https://github.com/scs/substraTEE-node.git", default-features = false, features=["no_global_allocator"] }
my_node_runtime = { package = "substratee-node-runtime", git = "https://github.com/scs/substraTEE-node.git", branch = "brenzi-contract", default-features = false, features=["no_global_allocator"] }
#keyring = { package = "substrate-keyring",git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false}
#node-primitives = { git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io" }

#contract
#contract = { package = "substratee-contract", path = "./contract/", default-features = false, features = ["core"]}
balances = { package = "srml-balances", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false}
contract = { package = "srml-contract", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false, features = ["core"]}
timestamp = { package = "srml-timestamp", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }
system = { package = "srml-system", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }
srml_support = { package = "srml-support", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }
#aura = { package = "srml-aura", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }

indices = { package = "srml-indices", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract-replace-sr-io", default-features = false }

#executor
#state_machine = { package = "substrate-state-machine", git = "https://github.com/brenzi/substrate.git", branch = "brenzi-contract", default-features = false }

parity-wasm = { version = "0.31", default-features = false }
